
project_id = "jixmwjplysaqlyzhpcmk"

[functions.track-event]
verify_jwt = false

[functions.fetch-rankings]
verify_jwt = false

[functions.schedule-rankings]
verify_jwt = false

[functions.get-country-from-ip]
verify_jwt = false
