name: Sync and Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy source files to temp directory
        run: |
          mkdir /tmp/source
          rsync -av --exclude='.git' --exclude='netlify.toml' ./ /tmp/source/

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: oterdimanx/reference-web
          ref: main
          token: ${{ secrets.GH_PAT }}
          path: target-repo

      - name: Prepare sync branch in target repo
        run: |
          cd target-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin sync-to-target || true
          if git show-ref --verify --quiet refs/remotes/origin/sync-to-target; then
            git checkout sync-to-target
            git pull origin sync-to-target --rebase
          else
            git checkout -b sync-to-target
          fi

      - name: Sync source to target repo
        run: |
          rsync -av --delete --exclude='.git' --exclude='netlify.toml' /tmp/source/ ./target-repo/
          cd target-repo
          git add .
          timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          git diff-index --quiet HEAD || git commit -m "Automated sync from reference-web-966b2c83 at $timestamp"
          git push origin sync-to-target

      - name: Create Pull Request in target repo
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          repository: oterdimanx/reference-web
          base: main
          head: sync-to-target
          title: "Automated sync from reference-web-966b2c83"
          body: "This PR contains automated changes."
